#Examples of environments vars

KC_URL="https://keycloak.domain.com"
KC_REALM="<KeyCloak_Realm_name>"                  
KC_CLIENT_ID="admin-cli"                                # Default client in master realm for connect ot KK via kk_user
KC_ADMIN_USER="matrix-groups-viewer"                    # Created user in master realm
KC_ADMIN_PASS="<KeyCloak user pass>"
KC_GROUP_NAME="matrix-users"                            # Keycloak group from which users will be synchronized with the chat

MATRIX_URL="https://matrix.domain.com"                  # URL Matrix homeserver
MATRIX_ADMIN_TOKEN="<Matrix_generated_token_via_mas>"   # Access token Matrix-
MATRIX_SERVER_NAME="matrix.domain.com"                  # Matrix server name

#In script hardcoded as false
#DRY_RUN=true
